name: Libfstcpp Regression Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regression:
    name: Build and Run Regression
    runs-on: ubuntu-latest
    container:
      image: verilator/verilator:v5.050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake ninja-build libgtest-dev lcov liblz4-dev patch

      - name: Run tests
        run: ./run_regression.sh --coverage
